### ISSUE TITLE
Why the ZeroTier Systemd Manager?

### ISSUE THREAD

**Issue by tcurdt** [zerotier/zeronsd#125]
I looked at [the quickstart](https://github.com/zerotier/zeronsd/blob/main/docs/quickstart.md) - but I don't get the need for the "ZeroTier Systemd Manager" install.

What's the difference to just run `zeronsd` through `systemd`?

Would be great to expand on this in the quickstart.

**Comment by erikh** [comment]
the systemd manager allows us to manage your resolvectl settings for systemd-resolved. It has very little to do with zeronsd directly, just DNS resolution on a per-network basis on linux, which is incapable of doing this without systemd-resolved (e.g., resolv.conf cannot provide per-interface DNS resolving capability). Compare with windows and OS X, which do not need such an agent, because they do it natively.

Closing this ticket as answered; if @someara is feeling up to updating the quickstart I am all for it, but I think we can link to this response for similar questions later. I want to say this is already answered in the various READMEs for the two projects as well.

-Erik

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tcurdt** [comment]
Ah! OK.

Sorry that I have missed those READMEs. Can you maybe add a link to them here for future reference?

I only found

> Linux users are strongly encouraged to use systemd-networkd along with systemd-resolved to get per-interface resolvers that you can isolate to the domain you want to use. If you'd like to try something that can assist with getting you going quickly, check out the zerotier-systemd-manager repository.

**Comment by erikh** [comment]
https://github.com/zerotier/zeronsd
https://github.zom/zerotier/zerotier-systemd-manager

scroll down a bit for both

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tcurdt** [comment]
IMO https://github.com/zerotier/zeronsd only answers this only when you know what you are looking for.
The README at  https://github.com/zerotier/zerotier-systemd-manager is more clear.
I would still suggest to add a sentence to the quickstart.
But I am fine now :)
Thanks
