### ISSUE TITLE
Better doc please

### ISSUE THREAD

**Issue by Vartkat** [zerotier/zeronsd#31]
Hello,

If I may...

At least me need better explanations, as I love Zerotier I was looking for this but I'm coming to my knowledge limits.
We have to tell clearly that each install method are exclusive (nothing is obvious).

A- Linux install
   A1- Cargo Install
       Prerequisites : - A linux running Debian
                                - A rust env (link to how to install on Debian)
                                - A Zerotier central token (where to find it or where to generate it + how to make the token file, should it be an export ZEROTIER_CENTRAL_TOKEN="xyz" bash script or a simple plain text containing the token ?)
                                - ZT hosts setup...(I imagine names in ZT central UI should not have spaces or if they can how do they translate in domain name ?)
        Install steps : -
                              -
        Verify steps : -
                              -
  ____________________
   A2- Docker install
             .
             .
(here, a portainer yaml file would be nice:-) )
 _____________________             .
B- OS X Install
             .
             .
             .
__________________
C- Windows Install
             .
             .
             .
_________________
D- Common error messages and how to deal with each

I don't mean to seem bossy, but I'm lost. I tried the cargo method on a Turnkey-core and I got
```
Welcome to ZeroNS!
Your IP for this network: fd9f:77fc:xxxx:xxxx:xxxxe
error syncing members: error in response: status code 403 Forbidden
Error: error in response: status code 403 Forbidden        
```      
I discovered that the existing token in ZT central was not the one I needed, and that I had to generate a new one...
The I got 

```
Welcome to ZeroNS!
Your IP for this network: fd9f:77fc:xxxx:xxxx:xxxxe
error configuring authority: unrecognized char:
PTR records are not supported on IPv6 networks (yet!)

error configuring authority: unrecognized char:
```
and also I discovered that the command line is active so if I CTRL-C I kill it... 
See... These must be beginers problems but I didn't resolve any and trying 
$ host MemberName.domain ZdnsRunningHost
doesn't give me any answer.

Hope this helps

Regards

V.

**Comment by erikh** [comment]
I'll try to address some of your comments here as I read them in the original message in a briefer format. Thanks for your report!

First things first, be advised that zeronsd is alpha software; currently aimed at advanced users that can troubleshoot problems in their own networks. It may not be ready for you quite yet given some of the problems I see you're having, but I'll attempt to assist.

Regarding packaging; we have packages for the following operating systems and containers:

- Docker amd64
- Windows amd64
- Linux amd64
  - Debian (`*.deb`)
  - Redhat (`*.rpm`)
- Finally, we have a crate on crates.io you can install.
- And the source itself.

If you desire another packaging format or container image, etc, please advise me in an independent ticket. A pull request with the packaging you're interested in would be my ideal situation.

Creating text fles for the token, and setting things in your environment, as well as typical unix idioms like pressing Ctrl+C to exit foreground programs is what makes me think you may not be interested in this software just yet. These are pretty basic things in a unix environment.

On to the error messages. I need to update this as 6plane and rfc4193 are currently broken entirely with zeronsd, and direct allocation ipv6 I was having trouble with too.

You need a central administrator token to run the daemon, I think it's pretty clear from the documentation that you do. Whether or not it should continue to run when your token is busted is another subject entirely. I might put in a bug for that later.

If you have more bugs to file, I strongly suggest independently filing them as separate issues, instead of combining them all into one ticket. I'm going to close this issue with my explanations and create separate tickets for the things that need to be done as stated in this reply.

Best of luck using the product. I realize it's not ready for everyone, but that's why it's in alpha.

**Comment by someara** [comment]
Hi vartkat, check out this repo. https://github.com/zerotier/zeronsd-quickstart
I
